@ECHO OFF

IF /I "%1" == "STDIN" (
  GOTO :STDINTEST
) ELSE IF /I "%1" == "TIMEOUT2" (
  GOTO :TIMEOUTTEST2
) ELSE IF /I "%1" == "TIMEOUT10" (
  GOTO :TIMEOUTTEST10
) ELSE IF /I "%1" == "BIGDATA" (
  GOTO :BIGDATA
)

EXIT 0

:STDINTEST
SET /P "INPUTDATA="
ECHO STDIN DATA: %INPUTDATA%
EXIT 0

:TIMEOUTTEST2
ping -n 2 127.0.0.1 > NUL
EXIT 2

:TIMEOUTTEST10
ping -n 10 127.0.0.1 > NUL
EXIT 0

:BIGDATA
FOR /L %%G IN (1, 1, 400000) DO ECHO ALICEWASBEGINNINGTOGETVERYTIREDOFSITTINGBYHERSISTERONTHEBANKANDO
EXIT 0
