## Compile-time configuration options for chronos that control the availability
## of various strictness and debuggability options. In general, debug helpers
## are enabled when `debug` is defined while strictness options are introduced
## in transition periods leading up to a breaking release that starts enforcing
## them and removes the option.
##
## `chronosPreviewV5` is a preview flag to enable v5 semantics - see below for
## the strictness checks it adds.
##
## `chronosDebug` can be defined to enable several debugging helpers that come
## with a runtime cost - it is recommeneded to not enable these in production
## code.
##
## In this file we also declare feature flags starting with `chronosHas...` -
## these constants are declared when a feature exists in a particular release -
## each flag is declared as an integer starting at 0 during experimental
## development, 1 when feature complete and higher numbers when significant
## functionality has been added. If a feature ends up being removed (or changed
## in a backwards-incompatible way), the feature flag will be removed or renamed
## also - you can use `when declared(chronosHasXxx): when chronosHasXxx >= N:`
## to require a particular version.
const
  chronosHandleException* {.booldefine.}: bool = false
    ## Remap `Exception` to `AsyncExceptionError` for all `async` functions.
    ##
    ## This modes provides backwards compatibility when using functions with
    ## inaccurate `{.raises.}` effects such as unannotated forward declarations,
    ## methods and `proc` types - it is recommened to annotate such code
    ## explicitly as the `Exception` handling mode may introduce surprising
    ## behavior in exception handlers, should `Exception` actually be raised.
    ##
    ## The setting provides the default for the per-function-based
    ## `handleException` parameter which has precedence over this global setting.
    ##
    ## `Exception` handling may be removed in future chronos versions.

  chronosSyncContinuations* {.booldefine.}: bool = false
    ## When enabled, `CallbackFlag.Continuation` callbacks of futures with
    ## `FutureFlag.SyncContinuations` are scheduled to run before processing
    ## other already queued events such as timer handlers and I/O.
    ##
    ## This feature is experimental and may be removed in future releases.

  chronosStrictFutureAccess* {.booldefine.}: bool = defined(chronosPreviewV5)

  chronosStackTrace* {.booldefine.}: bool = defined(chronosDebug)
    ## Include stack traces in futures for creation and completion points

  chronosFutureId* {.booldefine.}: bool = defined(chronosDebug)
    ## Generate a unique `id` for every future - when disabled, the address of
    ## the future will be used instead

  chronosFutureTracking* {.booldefine.}: bool = defined(chronosDebug)
    ## Keep track of all pending futures and allow iterating over them -
    ## useful for detecting hung tasks

  chronosDumpAsync* {.booldefine.}: bool = defined(nimDumpAsync)
    ## Print code generated by {.async.} transformation

  chronosProcShell* {.strdefine.}: string =
    when defined(windows):
      "cmd.exe"
    else:
      when defined(android):
        "/system/bin/sh"
      else:
        "/bin/sh"
    ## Default shell binary path.
    ##
    ## The shell is used as command for command line when process started
    ## using `AsyncProcessOption.EvalCommand` and API calls such as
    ## ``execCommand(command)`` and ``execCommandEx(command)``.

  chronosEventsCount* {.intdefine.} = 64
    ## Number of OS poll events retrieved by syscall (epoll, kqueue, poll).

  chronosInitialSize* {.intdefine.} = 32
    ## Initial size of Selector[T]'s array of file descriptors.

  chronosEventEngine* {.strdefine.}: string =
    when defined(nimdoc):
      ""
    elif defined(emscripten):
      "poll"
    elif defined(android):
      "epoll"
    elif defined(linux):
      "epoll"
    elif defined(macosx) or defined(macos) or defined(ios) or
          defined(freebsd) or defined(netbsd) or defined(openbsd) or
          defined(dragonfly) or defined(haiku):
      "kqueue"
    elif defined(posix):
      "poll"
    else:
      ""
    ## OS polling engine type which is going to be used by chronos.

  chronosHasRaises* = 0
    ## raises effect support via `async: (raises: [])`

  chronosTransportDefaultBufferSize* {.intdefine.} = 4096
    ## Default size of chronos transport internal buffer.

  chronosStreamDefaultBufferSize* {.intdefine.} = 16384
    ## Default size of chronos async stream internal buffer.

  chronosTLSSessionCacheBufferSize* {.intdefine.} = 4096
    ## Default size of chronos TLS Session cache's internal buffer.

  chronosUseSink* {.booldefine.} = (NimMajor, NimMinor, NimPatch) >= (2, 0, 6)
    ## Whether or not to use `sink` - using a recent Nim version helps:
    ## * https://github.com/nim-lang/Nim/issues/23354
    ## * https://github.com/nim-lang/Nim/issues/22175
    ##
    ## https://github.com/nim-lang/Nim/issues/12340 is a particularily serious
    ## bug but it does not affect chronos' usage as long as values are not
    ## moved out of Future (at the time of writing we only move values)

  chronosStrictReentrancy* {.booldefine.} = defined(chronosPreviewV5)
    ## Raise an assert if `poll` is re-entered by calling it from an `{.async.}`
    ## function or `callSoon` callback.
    ##
    ## Reentrancy is undefined behavior and generally not allowed in the chronos
    ## runtime - enbling this option will cause a panic if it's detected - this
    ## will become the default in future chronos versions.

when defined(chronosStrictException):
  {.warning: "-d:chronosStrictException has been deprecated in favor of handleException".}
  # In chronos v3, this setting was used as the opposite of
  # `chronosHandleException` - the setting is deprecated to encourage
  # migration to the new mode.

when defined(debug) or defined(chronosConfig):
  import std/macros

  static:
    hint("Chronos configuration:")
    template printOption(name: string, value: untyped) =
      hint(name & ": " & $value)
    printOption("chronosHandleException", chronosHandleException)
    printOption("chronosStackTrace", chronosStackTrace)
    printOption("chronosFutureId", chronosFutureId)
    printOption("chronosFutureTracking", chronosFutureTracking)
    printOption("chronosDumpAsync", chronosDumpAsync)
    printOption("chronosProcShell", chronosProcShell)
    printOption("chronosEventEngine", chronosEventEngine)
    printOption("chronosEventsCount", chronosEventsCount)
    printOption("chronosInitialSize", chronosInitialSize)
    printOption("chronosTransportDefaultBufferSize",
      chronosTransportDefaultBufferSize)
    printOption("chronosStreamDefaultBufferSize",
      chronosStreamDefaultBufferSize)
    printOption("chronosTLSSessionCacheBufferSize",
      chronosTLSSessionCacheBufferSize)

when chronosUseSink:
  template chronosSink*(T: type): type = sink T
  template chronosMoveSink*(v: sink auto): untyped = move(v)
else:
  template chronosSink*(T: type): type = T
  template chronosMoveSink*(v: sink auto): untyped = v
