name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: '42ef70c2102a942c46f13eb76872326edd525cec'
      test-command: |
        nimble install -y libbacktrace
        nimble test
        nimble test_libbacktrace
        nimble examples
