name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: nitely/nimbus-common-workflow/.github/workflows/common.yml@cache_doc
    with:
      test-command: |
        nimble install -y libbacktrace
        nimble test
        nimble test_libbacktrace
        nimble examples
        nimble api_docs
